general {
    lock_cmd = pidof hyprlock || hyprlock          # Avoid starting multiple hyprlock instances
    before_sleep_cmd = hyprlock                    # Lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on    # Restore display after suspend
}

listener {
    timeout = 150                                 # 2.5 min
    on-timeout = test ! -f /tmp/hypr-caffeine-state && brightnessctl -s set 6
    on-resume = brightnessctl -r
}

listener {
    timeout = 150                                 # 2.5 min
    on-timeout = test ! -f /tmp/hypr-caffeine-state && /usr/bin/brightnessctl -sd tpacpi::kbd_backlight set 0
    on-resume = /usr/bin/brightnessctl -rd tpacpi::kbd_backlight
}

listener {
    timeout = 300                                 # 5 min
    on-timeout = test ! -f /tmp/hypr-caffeine-state && (pidof hyprlock || hyprlock)
}

listener {
    timeout = 600                                 # 10 min
    on-timeout = test ! -f /tmp/hypr-caffeine-state && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
    timeout = 900                                 # 15 min
    on-timeout = test ! -f /tmp/hypr-caffeine-state && loginctl suspend
}

