#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Essentials
# exec-once = nm-applet &
exec-once = hyprpaper & waybar
exec-once = hypridle

# Authentication & Security
# Pour le polkit (ie. auth en root pour certaines apps)
exec-once = /usr/libexec/polkit-mate-authentication-agent-1

# Notifications
#exec-once = swaync
exec-once = swayosd-server

# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = ~/.config/hypr/scripts/wl-clip-persist --clipboard regular

# Plugins & Tools
# Plugins (buildés from scratch)
exec-once = hyprctl plugin load /usr/lib/hyprland/plugins/hyprbars.so
# Quickshell
exec-once = qs -c overview
exec-once = qs -c network
exec-once = qs -c panel
# Pypr (pour le fullscreen centering)
exec-once = /usr/bin/pypr

# Scripts
