#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

# Cursor
env = XCURSOR_THEME,CapitaineCursors
env = XCURSOR_SIZE,32
env = HYPRCURSOR_SIZE,32
env = GDK_SCALE,1.3
env = QT_SCALE_FACTOR,1
xwayland {
    force_zero_scaling = true
}

# GTK Theme (Gruvbox)
env = GTK_THEME,Gruvbox-Dark
env = GTK_ICON_THEME,Adwaita

# Wayland forcing
# Force Wayland for Electron apps
env = ELECTRON_OZONE_PLATFORM_HINT,auto
# Force Wayland for various toolkits
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
# Forcer Qt à utiliser qt6ct pour la configuration des thèmes
env = QT_QPA_PLATFORMTHEME,qt6ct
# Firefox/Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Directories
# Screenshot directory
env= HYPRSHOT_DIR,/home/pandora/Images/Screenshots


###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus 
$menu = rofi -show drun -icon-theme "Papirus" 
$colorpicker = hyprpicker -a
