###############
### PLUGINS ###
###############

plugin {  
    hyprbars {  
        # General bar settings  
        enabled = true  
        bar_height = 26  
        bar_color = rgba(29, 32, 33, 0.92) 
        bar_blur = yes
        col.text = rgb(ebdbb2)         # Gruvbox light foreground    
        bar_text_font = JetBrainsMono Nerd Font  
	      bar_part_of_window = yes

        # Buttons (right-to-left) - format: bgcolor, size, icon, action, fgcolor  
        hyprbars-button = rgb(FB2E2B), 14, , hyprctl dispatch killactive, rgb(ffffff)     # red: close
        hyprbars-button = rgb(F9A827), 14, , pypr layout_center toggle, rgb(000000)   # yellow: fullscreen
        hyprbars-button = rgb(A8B024), 14, , hyprctl dispatch togglefloating, rgb(000000) # green: floating
        inactive_button_color = rgb(A59682)

        # Double-click action on the bar  
        on_double_click = hyprctl dispatch fullscreen 1  exec, pypr layout_center toggle 
  
        # Spacing between buttons  
        bar_button_padding = 5  
    }
}


###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
