# FONTS
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

# GRUVBOX
include ./kitty_gruvbox_theme/gruvbox_dark_harder.conf

# SCROLL
scrollback_pager_history_size 10000

# MULTIPLE TABS
tab_bar_edge top
tab_bar_min_tabs 1

# NOTIFS
notify_on_cmd_finish invisible 10

# SHELL
shell .
# Active le remote control
allow_remote_control yes
# limite au socket local pour la sécurité
listen_on unix:/tmp/mykitty

# PADDING
window_padding_width 20 10 20 10

# CURSOR
cursor_trail 1
cursor_trail_start_threshold 0 
cursor_trail_decay 0.1 0.4

# Ctrl+Shift+E → envoie ESC [ 69 ; 5 u (pour toggle le file explorer nvim)
map ctrl+shift+e send_text all \x1b[69;5u
